version: "2.0"
volumes:
  mysql:
  html:
networks:
  frontend:
services:
  mysql:
    build: ./mysql
  php:
    build: ./php
    volumes:
      - html:/var/www/html
    networks:
      - frontend  
  apache:
    build: ./apache
    volumes:
      - html:/var/www/html
    networks:
      - frontend  
    ports:
      - "80:80"
    depends_on:
      - php
      - mysql
