version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.4
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_prestashop
      - MARIADB_DATABASE=bitnami_prestashop
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  prestashop:
    image: docker.io/bitnami/prestashop:1.7
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - PRESTASHOP_HOST=localhost
      - PRESTASHOP_DATABASE_HOST=mariadb
      - PRESTASHOP_DATABASE_PORT_NUMBER=3306
      - PRESTASHOP_DATABASE_USER=bn_prestashop
      - PRESTASHOP_DATABASE_NAME=bitnami_prestashop
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'prestashop_data:/bitnami/prestashop'
    depends_on:
      - mariadb
   hostname:
    image: 'balenablocks/hostname:latest'
    restart: unless-stoped
    network_mode: host
    labels:
      io.balena.features.supervisor-api: '1'
    environment:
      SET_HOSTNAME: prestashop
  hetzner-ddns:
    image: 'kutzilla/hetzner-ddns:latest'
    container_name: hetzner-ddns
    network_mode: host
    privileged: true
    environment:
      XDEBUG_ENABLED: ''
      RECORD_TYPE: A
      API_TOKEN: UZgSPSuRL4Uvz3be2UdST5y2XWlUhOec
      ZONE_NAME: mioga.eu
      RECORDE_NAME: dev
    restart: always      
volumes:
  mariadb_data:
    driver: local
  prestashop_data:
    driver: local
